<a href="https://colab.research.google.com/github/MaazUliman/web-scraping-pandas/blob/main/Project_1_Web_Scraping_With_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df_premier21 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2526/E0.csv")

In [4]:
df_premier21.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [6]:
df_premier21.rename(columns = {"FTAG":"away_goals","FTHG":"home_goals"},inplace = True)

In [7]:
df_premier21.head()

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [11]:
root = "https://www.football-data.co.uk/mmz4281/"

In [ ]:
https://www.football-data.co.uk/mmz4281/2526/E0.csv

In [13]:
leagues = ["E0","E1","E2","E3","EC"]
frames = []
for league in leagues:
  df = pd.read_csv(root + "2122" + "/" + league + ".csv",encoding = "unicode_escape")
  frames.append(df)

In [14]:
frames[0].head()

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86

In [15]:
frames[1].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,06/08/2021,19:45,Bournemouth,West Brom,2,2,D,1,1,...,1.84,-0.25,2.13,1.78,2.13,1.80,2.16,1.83,2.09,1.77
1,E1,07/08/2021,15:00,Blackburn,Swansea,2,1,H,1,0,...,1.70,-0.25,1.77,2.14,1.83,2.09,1.87,2.17,1.81,2.04
2,E1,07/08/2021,15:00,Bristol City,Blackpool,1,1,D,1,0,...,1.66,-0.25,1.90,2.00,1.92,1.99,1.92,2.01,1.89,1.95
3,E1,07/08/2021,15:00,Cardiff,Barnsley,1,1,D,0,0,...,1.62,-0.25,2.05,1.75,2.14,1.80,2.19,1.80,2.11,1.75
4,E1,07/08/2021,15:00,Derby,Huddersfield,1,1,D,1,1,...,1.60,-0.25,1.88,2.02,1.88,2.01,1.90,2.07,1.87,1.98

In [16]:
len(frames)

5

In [20]:
leagues = ["E1","E2","E3"]
frames = []
for league in leagues:
  for season in range(20,26):
    df = pd.read_csv(root + str(season)+str(season+1) + "/" + league + ".csv",encoding = "unicode_escape")
    df.insert(1,"Season",season)
    frames.append(df)

In [21]:
len(frames)

18

In [22]:
frames[0].head()

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,20,11/09/2020,19:45,Watford,Middlesbrough,1,0,H,1,...,1.65,-0.50,2.05,1.85,2.04,1.85,2.09,1.88,2.02,1.82
1,E1,20,12/09/2020,12:30,Birmingham,Brentford,1,0,H,1,...,1.67,0.50,1.97,1.93,1.96,1.93,1.97,1.99,1.91,1.93
2,E1,20,12/09/2020,12:30,Wycombe,Rotherham,0,1,A,0,...,1.86,0.25,1.99,1.91,1.95,1.93,2.04,1.98,1.93,1.92
3,E1,20,12/09/2020,15:00,Barnsley,Luton,0,1,A,0,...,1.83,-0.50,1.77,2.02,1.81,2.10,1.87,2.14,1.80,2.05
4,E1,20,12/09/2020,15:00,Bournemouth,Blackburn,3,2,H,1,...,1.89,-0.50,2.06,1.84,2.07,1.85,2.11,1.90,2.02,1.83

In [23]:
frames[17].head()

,ï»¿Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,Unnamed: 132
0,E3,25,02/08/2025,15:00,Accrington,Gillingham,1,1,D,0,...,1.88,1.76,2.12,1.98,1.88,1.92,1.83,2.09,1.88,NaN
1,E3,25,02/08/2025,15:00,Barnet,Fleetwood Town,0,2,A,0,...,1.85,2.29,1.65,2.08,1.85,2.00,1.74,2.04,1.93,NaN
2,E3,25,02/08/2025,15:00,Bristol Rvs,Harrogate,0,1,A,0,...,2.03,1.85,2.00,1.85,2.03,1.78,1.96,1.88,2.12,NaN
3,E3,25,02/08/2025,15:00,Cambridge,Cheltenham,1,0,H,0,...,1.88,1.88,1.97,1.98,1.88,1.90,1.83,1.98,2.00,NaN
4,E3,25,02/08/2025,15:00,Chesterfield,Barrow,1,0,H,1,...,2.03,1.79,2.06,1.80,2.07,1.73,2.02,1.87,2.13,NaN